version: "3"
services:
  appserver:
    container_name: server
    hostname: localhost
    image: alpha110r/spring-project:alon-007.2
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    privileged: true